### ISSUE TITLE
more low level decoding

### ISSUE THREAD

**Issue by jimmywarting** [rvagg/cborg#67]
Hi, this pkg looks neat. but it wasn't as low level as i would have hope. 
I want to decode a buffer partially in steps... i would like to iterate over each Token and want to read data more manually and search around.
I would like to jump around with offsets and skip reading particular sections.

eg: i would like to read one token, realize that it's a byte array, knowing how large the buffer is and skip reading n bytes. without having that particular buffer in memory. i want to be able to search inside of my bundle

I assume i'm after the `toToken` functionality but also without the 
`assertEnoughData` and `slice` method... just wanna know how large the byte array is...

**Comment by rvagg** [comment]
I think this section would be getting in the way: https://github.com/rvagg/cborg/blob/f05397b8df2d7a063f0d35cc756d74ce5cb2f4f1/lib/decode.js#L38-L47

What you'd need is to be able to intercept this flow with an interest in a particular major (and possibly minor too) with a custom function that may or may not defer down in to the real decoder. e.g. being able to register that you're interested in all major `2` tokens with an intercepting function that can make a decision about whether to defer to the real byte decoders or return a fake bytes token and use `encodedLength` to skip forward.

It would be an interesting exercise in extensibility; my concern about adding these extension points is the cost in always checking "do I need to branch here?" when the most common case I care about is without the extensions.

**Comment by jimmywarting** [comment]
I found a old [diagnostic](https://github.com/apowers313/cbor-pretty-print/tree/9623f1b922f9228b2d47a4bc9a29d020f8c5cf36) package that had util function for getting a cbor byte length that solved my current problem:

```js
const CBOR_MAJOR = {
  UNSIGNED_INT: 0x00,
  NEGATIVE_INT: 0x20,
  BYTE_STRING: 0x40,
  TEXT_STRING: 0x60,
  ARRAY: 0x80,
  MAP: 0xa0,
  SEMANTIC_TAG: 0xc0,
  VALUE: 0xe0
}

const CBOR_MASK = {
  MAJOR: 0xE0,
  LENGTH: 0x1F
}

const CBOR_LENGTH = {
  ONE: 0x18,
  TWO: 0x19,
  THREE: 0x1A,
  INDEFINITE: 0x1F
}

export function getCborLength (cbor) {
  const len = cbor[0] & CBOR_MASK.LENGTH
  if (len < CBOR_LENGTH.ONE) {
    return {
      length: len,
      bytes: 1
    }
  }
  switch (len) {
    case CBOR_LENGTH.ONE:
      return {
        length: cbor[1],
        bytes: 2
      }
    case CBOR_LENGTH.TWO:
      return {
        length: cbor[1] << 8 | cbor[2],
        bytes: 3
      }
    case CBOR_LENGTH.THREE:
      return {
        length: cbor[1] << 16 | cbor[1] << 8 | cbor[3],
        bytes: 4
      }
    case CBOR_LENGTH.INDEFINITE:
      throw new Error('Indefinite length unhadled')
    default:
      throw new Error('Invalid length?')
  }
}
```
